---
title: "PCA R Packages"
author: "Karl Rohe"
date: "2024-01-15"
output: html_document
editor_options: 
  chunk_output_type: console
---




```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r, include=FALSE}
#> r = getOption("repos")
#> r["CRAN"] = "http://cran.us.r-project.org"
#> options(repos = r)
```



```{r, cache=TRUE}
library(tidyverse)
library(longpca)
#> all_packages = available.packages() %>% as_tibble()
all_packages
top_packages
```

```{r}
im_description = make_interaction_model(~Package*Description, top_packages, parse_text = TRUE, to_lower= TRUE)
diagnose(im_description)
dimcv = pick_dim(im_description, 20,num_bootstraps = 10)
plot(dimcv)
dimcv
pcs = pca(im_description, 6)
streaks(pcs)
spcs = rotate(pcs)
streaks(spcs)
streaks(spcs,"cols")
top(spcs,2)
top(spcs,3)
top(spcs,4)
top(spcs,5)
```


```{r}
im_authors = make_interaction_model(~Package*Author, top_packages, parse_text = TRUE, to_lower= TRUE)
im_authors
diagnose(im_authors)
dimcv = pick_dim(im_authors, 20,num_bootstraps = 10)
plot(dimcv)
dimcv
pcs_authors = pca(im_authors, 10)
streaks(pcs_authors)
spcs_authors = rotate(pcs_authors)
streaks(spcs_authors)
streaks(spcs_authors, "cols")
```





```{r}
sptext = make_interaction_model(~Package*Imports, all_packages, parse_text = TRUE)
```

```{r, cache = TRUE}
diagnose(sptext)
pcs = pca_text(1~Package*Imports, all_packages, k = 10)
spcs = rotate(pcs)
top(pcs,1)
top(spcs,1)
```
